### ISSUE TITLE
Add comparison to Themosis

### ISSUE THREAD

**Issue by mindfullsilence** [htmlburger/wpemerge-theme-docs#1]
This lib looks awesome!!

Saw the [comparison chart here](https://github.com/htmlburger/wpemerge-theme-docs#comparison-table) and after reading through the docs I think it makes sense to add a column for [Themosis](https://framework.themosis.com/), which is another OOP library that looks as robust as wpemerge. I haven't used either yet but am wondering what the differences/pros/cons are to each.

**Comment by atanas-angelov-dev** [comment]
Hi @mindfullsilence ,

These are the docs for a yet unreleased theme that is subject to change. We will update the comparisons etc. anyway upon release.

In the meantime, you can check out the underlying framework which is available (albeit no 1.0 release yet) - https://docs.wpemerge.com/
